backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Nawigacja"
    folder: "src"
    extension: "json"
    format: "json"
    create: false
    slug: "menu"
    files:
      - label: "Lista Menu"
        name: "menu_list"
        file: "src/menu.json"
        fields:
          - {label: "Linki", name: "links", widget: "list", fields: [
              {label: "Napis", name: "napis", widget: "string"},
              {label: "Link", name: "link", widget: "string"}
            ]}
