backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Nawigacja"
    file: "src/menu.json"
    fields:
      - label: "Linki Menu"
        name: "links"
        widget: "list"
        fields:
          - { label: "Napis", name: "napis", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
