backend:
  name: github
  repo: kidiee558/PLANSTREETFOOD-PODGLAD
  branch: main
  base_url: https://api.netlify.com 
  auth_endpoint: auth
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - file: "src/data/menu.json"
        label: "Lista dań"
        name: "items"
        fields:
          - { label: "Nazwa", name: "name", widget: "string" }
          - { label: "Cena", name: "price", widget: "string" }
